dist: bionic

sudo: false

language: php

services:
  - mysql

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - main

matrix:
  include:
    - php: 7.3
      env: WP_VERSION=latest WP_TRAVISCI=phpcs
    - php: 7.4
      env: WP_VERSION=latest
    - php: 8.0
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_VERSION=trunk
  allow_failures:
    - php: 8.0
    - php: 7.3
      env: WP_VERSION=trunk

before_install:
  - |
    export PATH="$HOME/.composer/vendor/bin:$PATH"
    export WP_CORE_DIR="/tmp/wordpress/"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - composer install -n
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh "$(pwd)/vendor/alleyinteractive/mantle-framework/src/mantle/framework/testing/wp-tests-config-sample.php" wordpress_test root "" 127.0.0.1 "$WP_VERSION"
      mkdir "$WP_CORE_DIR/wp-content/private/"
      cp -R . "$WP_CORE_DIR/wp-content/private/mantle-site"
      cd "$WP_CORE_DIR/wp-content/private/mantle-site/"
    fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer run phpcs
    fi
  - |
    composer run phpunit
