name: Coding Standards

on:
  push:
    branches:
      - main
      - '*.*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  coding-standards:
    uses: alleyinteractive/.github/.github/workflows/php-coding-standards.yml@main
    with:
      php: '8.2'
