on:
  push:
    branches:
      - main
      - gh-action

  schedule:
    - cron: '0 */2 * * *'

name: create-mantle-app sync

jobs:
  copy-to-create-mantle-app:
    name: copy files to create-mantle-app
    runs-on: ubuntu-latest

    steps:
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          clean: true
          dst_branch: main
          dst_owner: alleyinteractive
          dst_path: /plugins/mantle-app/
          dst_repo_name: create-mantle-app
          email: mantle@alley.co
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_branch: main
          src_path: /
          username: alley-ci
