on:
  push:
    branches:
      - gh-action

  schedule:
    - cron: '0 */2 * * *'

name: sync-theme

jobs:
  sync-theme:
    name: sync theme
    runs-on: ubuntu-latest

    steps:
      - name: Copy Latest Theme
        shell: bash
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

          echo "Cloning create-mantle-app..."
          git clone --depth=1 https://$TOKEN@github.com/alleyinteractive/create-mantle-app.git create-mantle-app

          echo "Cloning theme..."
          git clone --depth=1 https://github.com/WordPress/WordPress.git wordpress

          echo "Removing old theme..."
          rm -rf create-mantle-app/themes/twentytwenty

          echo "Replacing theme..."
          mv wordpress/wp-content/themes/twentytwenty create-mantle-app/themes/twentytwenty
          rm -rf create-mantle-app/themes/twentytwenty/.git
          rm -rf create-mantle-app/themes/twentytwenty/.github

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes detected."
            exit 0
          fi

          echo "Committing..."
          cd create-mantle-app/themes
          git add -A
          git commit -m "Syncing twentytwenty"
          git push
