on:
  push:
    branches:
      - main

name: create-mantle-app sync

jobs:
  copy-to-create-mantle-app:
    name: copy files to create-mantle-app
    runs-on: ubuntu-latest

    steps:
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          commit_message: "Syncing from alleyinteractive/mantle"
          clean: true
          dst_branch: main
          dst_owner: alleyinteractive
          dst_path: /mu-plugins/mantle-app
          dst_repo_name: create-mantle-app
          exclude: |
            .github/*
            docs/*
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_branch: main
          src_path: /.
