name: Sync from create-wordpress-plugin

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      SOURCE_REPO: "alleyinteractive/create-wordpress-plugin"
      TARGET_REPO: "alleyinteractive/mantle"
      BRANCH_NAME: "sync/create-wordpress-plugin"
    steps:
      - name: Checkout mantle repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          fetch-depth: 0

      - name: Checkout create-wordpress-plugin repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SOURCE_REPO }}
          path: create-wordpress-plugin
          token: ${{ secrets.PERSONAL_TOKEN }}
          fetch-depth: 1

      - name: Configure Git
        run: |
          git config user.name "mantle-bot"
          git config user.email "actions@github.com"
          git checkout -B $BRANCH_NAME

      - name: Copy selected files
        run: |
            rsync -av --relative \
            ./create-wordpress-plugin/.editorconfig \
            ./create-wordpress-plugin/.github/workflows/all-pr-tests.yml \
            ./create-wordpress-plugin/.nvmrc \
            ./create-wordpress-plugin/.stylelintrc.json \
            ./create-wordpress-plugin/babel.config.js \
            ./create-wordpress-plugin/blocks/README.md \
            ./create-wordpress-plugin/entries/README.md \
            ./create-wordpress-plugin/jest.config.js \
            ./create-wordpress-plugin/jsconfig.json \
            ./create-wordpress-plugin/package-lock.json \
            ./create-wordpress-plugin/package.json \
            ./create-wordpress-plugin/phpunit.xml \
            ./create-wordpress-plugin/tsconfig.eslint.json \
            ./create-wordpress-plugin/tsconfig.json \
            ./ \
            --prune-empty-dirs

      - name: Modify package.json
        run: |
          sed -i 's/create-wordpress-plugin/mantle/g' package.json
          sed -i 's/create-wordpress-plugin/mantle/g' package-lock.json

      - name: Commit changes
        run: |
          rm -rf create-wordpress-plugin

          git add -N .
          if ! git diff --quiet; then
            git add .
            git commit -m "chore(sync): update files from create-wordpress-plugin"
            git push --force --set-upstream origin $BRANCH_NAME
          else
            echo "No changes to commit."
          fi

      - name: Create PR if it doesn't exist
        run: |
            if ! gh pr view --base main --repo "$TARGET_REPO" --head "$BRANCH_NAME" > /dev/null 2>&1; then
              gh pr create \
                --repo "$TARGET_REPO" \
                --base main \
                --head "$BRANCH_NAME" \
                --title "chore(sync): update files from create-wordpress-plugin" \
                --body "This PR syncs changes from the create-wordpress-plugin repository."
            else
              echo "PR already exists for branch $BRANCH_NAME."
            fi
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
